apiVersion: v1
kind: Pod
metadata:
  name: my-winston-app
spec:
  containers:
    - name: my-winston-app
      image: my-winston-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
      env:
        - name: NODE_ENV
          value: production
        - name: LOG_LEVEL
          value: info
